name: Build VictorIsCool clients

on:
  workflow_dispatch:
    inputs:
      upload_tag:
        description: Artifact/release tag label
        required: false
        default: victoriscool
        type: string
  push:
    branches:
      - "release/victoriscool-*"
      - "victor/clients-*"

permissions:
  contents: read
  actions: write

jobs:
  build-clients:
    uses: ./.github/workflows/flutter-build.yml
    with:
      upload-artifact: true
      upload-tag: victoriscool-1.0.0
    secrets: inherit
